version: 1.0.{build}
configuration: Release
platform: x64
clone_depth: 1
before_build:
- cmd: >-
    git submodule init

    git submodule update

    cmake -G "Visual Studio 14 2015 Win64" .
build:
  project: terraphast.sln
  verbosity: minimal
test_script:
- cmd: C:\projects\terraces\Release\unittests.exe
